### ISSUE TITLE
Open PRs

### ISSUE THREAD

**Issue by weex** [Giszmo/nostrResources#6]
I see a few attempts to contribute which are in limbo. I think this could be a great project, but think especially at the beginning it's important to merge almost every PR that's offered.

For more background on this concept, I recommend reading and to be more bold to adopt https://rfc.zeromq.org/spec/42/

**Comment by Giszmo** [comment]
I totally agree and have no idea why GitHub doesn't include these PRs in my notifications that I go threw religiously every day. Will figure out and be more responsive going forward!

**Comment by weex** [comment]
Right on, I'm happy to co-maintain as long as not a lot of review is required.

**Comment by Giszmo** [comment]
Oh, cool! If you review PRs and approve them, I'll probably merge them quickly. If you are interested in this, feel free to comment on your vision. You want more details or less? Or other? I find it's quickly getting complex.

**Comment by weex** [comment]
Sure, my vision is to follow C4 protocol as linked above.

The way it works is we do basic checks, like make sure it's not obviously broken and addresses a valid problem, and then we merge it. I went looking for the best defined, lightweight, easy process I could find for FOSS and found that. In my experience it works well and scales wonderfully.

**Comment by Giszmo** [comment]
I think there is no need to formalize anything at this point. All merged PRs were made by Danny who I paid to research the data. I'd happily merge more data if there was interest but so far I don't see that emerging.
